export const COOKIE_NAME = "casa_cultura_session";
export const ROLES = ["admin", "capturista", "consultor", "user"] as const;
export const GRUPOS_FUNCION = ["ADMO", "TECN", "SERV", "COMUN", "PROFE", "EDU"] as const;
export const NIVELES = ["federal", "estatal", "municipal", "otro"] as const;
export const CALIFICACION_APROBATORIA = 70;
export const CURSOS_REQUERIDOS_ACREDITACION = 2;

export const TIPO_PROGRAMA_LABELS: Record<string, string> = {
  PAC: "PAC",
  SPC: "SPC",
  SDPC: "SDPC",
};

// SPC y SDPC: finalidad fija, igual para todos sus cursos -- se deriva sola,
// no se captura. PAC: cada curso elige UNA de estas 4 (variable por curso,
// no una sola finalidad para todo el tipo) -- ver FINALIDADES_PAC.
export const FINALIDAD_POR_TIPO_PROGRAMA: Record<string, string> = {
  SPC: "Certificar",
  SDPC: "FACTOR FCAP (Factor Formación, Capacitación y Actualización Profesional)",
};

export const FINALIDADES_PAC = ["Actualizar", "Desarrollar", "Sensibilizar", "Fortalecer"] as const;

export const CATALOGO_ESTUDIOS = [
  "SIN ESTUDIOS",
  "PRIMARIA INCOMPLETA",
  "PRIMARIA TERMINADA",
  "PRIMARIA EN CURSO",
  "SECUNDARIA INCOMPLETA",
  "SECUNDARIA TERMINADA",
  "SECUNDARIA EN CURSO",
  "CARRERA COMERCIAL/SECRETARIAL",
  "TECNICO PROFESIONAL INCOMPLETO",
  "TECNICO PROFESIONAL TERMINADO",
  "TECNICO PROFESIONAL EN CURSO",
  "BACHILLERATO TECNOLOGICO INCOMPLETO",
  "BACHILLERATO TECNOLOGICO TERMINADO",
  "BACHILLERATO TECNOLOGICO EN CURSO",
  "BACHILLERATO INCOMPLETO",
  "BACHILLERATO TERMINADO",
  "BACHILLERATO EN CURSO",
  "ESCUELA NORMALISTA TERMINADA",
  "TSU* o PROFESIONAL ASOCIADO INCOMPLETO",
  "TSU* o PROFESIONAL ASOCIADO TERMINADO",
  "TSU* o PROFESIONAL ASOCIADO EN CURSO",
  "EDUCACION SUPERIOR o LICENCIATURA INCOMPLETA",
  "EDUCACION SUPERIOR o LICENCIATURA EN CURSO",
  "PASANTE DE EDUCACION SUPERIOR o LICENCIATURA",
  "EDUCACION SUPERIOR o LICENCIATURA TITULADO",
  "LICENCIATURA CON ESPECIALIDAD INCOMPLETA",
  "LICENCIATURA CON ESPECIALIDAD TERMINADA",
  "LICENCIATURA CON ESPECIALIDAD EN CURSO",
  "MAESTRIA INCOMPLETA",
  "MAESTRIA TERMINADA",
  "DOCTORADO INCOMPLETO",
  "DOCTORADO TERMINADO",
  "POSTDOCTORADO INCOMPLETO",
  "POSTDOCTORADO TERMINADO",
] as const;

export const CMAO_CATALOGO: { cmao: string; ua: string }[] = [
  { cmao: "CMAO1", ua: "COORDINACION DE PRESUPUESTO Y RECURSOS FINANCIEROS" },
  { cmao: "CMAO1", ua: "COORDINACION DE RECURSOS HUMANOS" },
  { cmao: "CMAO1", ua: "COORDINACION DE RECURSOS MATERIALES Y SERVICIOS GENERALES" },
  { cmao: "CMAO1", ua: "COORDINACION NACIONAL DE DESARROLLO INSTITUCIONAL" },
  { cmao: "CMAO1", ua: "DIRECCION DE CAPITAL HUMANO" },
  { cmao: "CMAO1", ua: "DIRECCION DE RELACIONES LABORALES" },
  { cmao: "CMAO2", ua: "CENTRO DE LA IMAGEN" },
  { cmao: "CMAO2", ua: "CENTRO NACIONAL DE LAS ARTES" },
  { cmao: "CMAO3", ua: "DIRECCION GENERAL DE BIBLIOTECAS" },
  { cmao: "CMAO4", ua: "DIRECCION GENERAL DE SITIOS Y MONUMENTOS DEL PATRIMONIO CULTURAL" },
  { cmao: "CMAO5", ua: "CENTRO NACIONAL PARA LA PRESERVACION DEL PATRIMONIO CULTURAL FERROCARRILERO" },
  { cmao: "CMAO5", ua: "COMPLEJO CULTURAL LOS PINOS Y BOSQUE DE CHAPULTEPEC" },
  { cmao: "CMAO5", ua: "COORDINACION DEL SISTEMA NACIONAL DE FOMENTO MUSICAL" },
  { cmao: "CMAO5", ua: "DIRECCIÓN GENERAL DE SISTEMA DE APOYOS A LA CREACIÓN DE PROYECTOS CULTURALES" },
  { cmao: "CMAO6", ua: "COORDINACION NACIONAL DE DESARROLLO CULTURAL INFANTIL" },
  { cmao: "CMAO6", ua: "SUBSECRETARIA DE DIVERSIDAD CULTURAL Y FOMENTO A LA LECTURA (CNPCT)" },
  { cmao: "CMAO7", ua: "CENTRO CULTURAL HELENICO" },
  { cmao: "CMAO7", ua: "DIRECCION GENERAL DE ASUNTOS INTERNACIONALES" },
  { cmao: "CMAO8", ua: "DIRECCION GENERAL DE CIRCUITOS Y FESTIVALES" },
  { cmao: "CMAO8", ua: "FONOTECA NACIONAL" },
  { cmao: "CMAO10", ua: "UNIDAD DE CULTURAS VIVAS, PATRIMONIO INMATERIAL E INTERCULTURALIDAD" },
  { cmao: "CMAO12", ua: "COORDINACION DE TECNOLOGIAS DE LA INFORMACION Y COMUNICACIONES" },
  { cmao: "CMAO13", ua: "DIRECCION GENERAL DE VINCULACION CULTURAL" },
  { cmao: "CMAO14", ua: "OFICINA DE LA C. SECRETARIA DE CULTURA" },
  { cmao: "CMAO15", ua: "UNIDAD DE ASUNTOS JURIDICOS" },
  { cmao: "CMAO16", ua: "DIRECCION DE DIFUSION CULTURAL" },
  { cmao: "CMAO17", ua: "INSTITUTO NACIONAL DEL DERECHO DE AUTOR" },
  { cmao: "CMAO18", ua: "RADIO EDUCACIÓN" },
];
